name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set current date as env variable
      run: echo "NOW=$(date +'%y%m%d')" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build -t hdh7485/mbti_test:$NOW . 
    - name: Push the Docker image
      run: docker push hdh7485/mbti_test:$NOW
